doc: Add a Quick Start section to the README
linode/linode_api4-python pull request #234
Opened 2023-04-06 15:14 UTC by lgarber-akamai

## 📝 Description

This change adds a quick start section to the project's README file. This section should reduce friction for new users by providing a usage example without the need to read through the full Getting Started guide.

2023-04-06 15:39 UTC, ezilber-akamai requested changes

2023-04-06 15:39 UTC, ezilber-akamai commented on README.rst
> +In order to authenticate the with the Linode API, you will first need to create a
Looks like you have a typo here.

2023-04-06 17:35 UTC, yec-akamai approved these changes
Thank you for adding this session! I think it clarifies a lot for a new user to get started ;)

2023-04-06 17:35 UTC, yec-akamai commented on README.rst
> +    client = LinodeClient("MYPERSONALACCESSTOKEN")
nit: the value maybe more readable in a snake or camel case?

2023-04-06 17:35 UTC, yec-akamai commented on README.rst
> +        "g6-nanode-1",
nit: may worth also specifying the attributes' names here so a new user can better understand, i.e. 
```
type="g6-nanode-1",
region="us-southeast",
```

2023-04-07 13:28 UTC, ezilber-akamai approved these changes

2023-04-10 16:04 UTC, merged