add examples for getting the password and IPv4
linode/linode_api4-python pull request #328
Opened 2023-09-15 19:56 UTC by WingsLikeEagles

## 📝 Description

Add three examples:
1. Output the new_linode root password
2. Output the new_linode IPv4 address
3. Delete the new_linode

## ✔️ How to Test

The comments explain how to test.

2023-09-15 19:58 UTC, WingsLikeEagles commented on linode_api4/groups/linode.py
> +        To delete the new_linode:
```suggestion
        To delete the new_linode (WARNING: this immediately destroys the Linode):
```

2023-09-18 19:08 UTC, lgarber-akamai requested changes
Thanks for the great contribution! Just one small change and this should be good to go

2023-09-18 19:08 UTC, lgarber-akamai commented on linode_api4/groups/linode.py
> +        To output the IPv4 address of the new Linode:
Since the `ipv4` attribute contains a list of all IPv4 addresses assigned to the Linode, could the wording here be updated to reflect that?

2023-09-19 15:56 UTC, jriddle-linode approved these changes
Looks good after Lena's feedback! :)

2024-02-05 16:33 UTC, yec-akamai approved these changes

2024-02-05 16:34 UTC, merged